services:
  common:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: common
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  attack:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: attack
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: unless-stopped

  payment:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: payment
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: gateway
    env_file:
      - .env
    environment:
      PROXY_CONFIG: config.docker.json
    ports:
      - "8080:8080"
    depends_on:
      - common
      - attack
      - payment
    restart: unless-stopped

  node-router:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: node-router
    env_file:
      - .env
    restart: unless-stopped
